// <auto-generated />
using ArcDamageCalculator.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArcDamageCalculator.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260324233254_AddNewGrenades")]
    partial class AddNewGrenades
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArcDamageCalculator.Api.Models.Grenade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Damage")
                        .HasColumnType("double precision");

                    b.Property<double?>("Delay")
                        .HasColumnType("double precision");

                    b.Property<double?>("Duration")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Radius")
                        .HasColumnType("double precision");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Grenades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Damage = 30.0,
                            Delay = 0.0,
                            Name = "Light Impact Grenade",
                            Radius = 2.5,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Damage = 80.0,
                            Delay = 3.0,
                            Name = "Heavy Fuze",
                            Radius = 7.5,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Damage = 70.0,
                            Delay = 3.0,
                            Name = "Snap Blast",
                            Radius = 7.5,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Damage = 5.0,
                            Duration = 10.0,
                            Name = "Blaze",
                            Radius = 10.0,
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Damage = 90.0,
                            Delay = 1.5,
                            Name = "Trigger 'Nade",
                            Radius = 7.5,
                            Type = 2
                        },
                        new
                        {
                            Id = 6,
                            Damage = 60.0,
                            Delay = 3.0,
                            Name = "Shrapnel Grenade",
                            Radius = 6.0,
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            Damage = 20.0,
                            Delay = 1.5,
                            Name = "Trailblazer",
                            Radius = 2.0,
                            Type = 2
                        });
                });

            modelBuilder.Entity("ArcDamageCalculator.Api.Models.Gun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Damage")
                        .HasColumnType("double precision");

                    b.Property<double>("FireRate")
                        .HasColumnType("double precision");

                    b.Property<double>("HeadshotMultiplier")
                        .HasColumnType("double precision");

                    b.Property<double>("LimbMultiplier")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("RelativeDps")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Guns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Damage = 8.5,
                            FireRate = 30.0,
                            HeadshotMultiplier = 2.5,
                            LimbMultiplier = 0.75,
                            Name = "Kettle",
                            RelativeDps = 280.0
                        },
                        new
                        {
                            Id = 2,
                            Damage = 9.0,
                            FireRate = 33.299999999999997,
                            HeadshotMultiplier = 2.0,
                            LimbMultiplier = 0.75,
                            Name = "Rattler",
                            RelativeDps = 299.69999999999999
                        },
                        new
                        {
                            Id = 3,
                            Damage = 9.5,
                            FireRate = 18.300000000000001,
                            HeadshotMultiplier = 2.0,
                            LimbMultiplier = 0.75,
                            Name = "Arpeggio",
                            RelativeDps = 173.90000000000001
                        },
                        new
                        {
                            Id = 4,
                            Damage = 10.0,
                            FireRate = 36.700000000000003,
                            HeadshotMultiplier = 1.5,
                            LimbMultiplier = 0.75,
                            Name = "Tempest",
                            RelativeDps = 367.0
                        },
                        new
                        {
                            Id = 5,
                            Damage = 14.0,
                            FireRate = 32.0,
                            HeadshotMultiplier = 2.0,
                            LimbMultiplier = 0.75,
                            Name = "Bettina",
                            RelativeDps = 448.0
                        },
                        new
                        {
                            Id = 6,
                            Damage = 40.0,
                            FireRate = 6.5999999999999996,
                            HeadshotMultiplier = 2.5,
                            LimbMultiplier = 0.75,
                            Name = "Ferro",
                            RelativeDps = 264.0
                        },
                        new
                        {
                            Id = 7,
                            Damage = 35.0,
                            FireRate = 21.0,
                            HeadshotMultiplier = 2.25,
                            LimbMultiplier = 0.75,
                            Name = "Renegade",
                            RelativeDps = 735.0
                        },
                        new
                        {
                            Id = 8,
                            Damage = 25.0,
                            FireRate = 9.0,
                            HeadshotMultiplier = 2.0,
                            LimbMultiplier = 0.75,
                            Name = "Aphelion",
                            RelativeDps = 216.0
                        },
                        new
                        {
                            Id = 9,
                            Damage = 6.5,
                            FireRate = 45.299999999999997,
                            HeadshotMultiplier = 1.75,
                            LimbMultiplier = 0.75,
                            Name = "Stitcher",
                            RelativeDps = 317.10000000000002
                        },
                        new
                        {
                            Id = 10,
                            Damage = 6.0,
                            FireRate = 66.700000000000003,
                            HeadshotMultiplier = 2.0,
                            LimbMultiplier = 0.75,
                            Name = "Bobcat",
                            RelativeDps = 400.0
                        },
                        new
                        {
                            Id = 11,
                            Damage = 67.5,
                            FireRate = 14.0,
                            HeadshotMultiplier = 1.5,
                            LimbMultiplier = 0.75,
                            Name = "Il Toro",
                            RelativeDps = 965.29999999999995
                        },
                        new
                        {
                            Id = 12,
                            Damage = 49.5,
                            FireRate = 26.300000000000001,
                            HeadshotMultiplier = 1.0,
                            LimbMultiplier = 0.75,
                            Name = "Vulcano",
                            RelativeDps = 1302.9000000000001
                        },
                        new
                        {
                            Id = 13,
                            Damage = 20.0,
                            FireRate = 9.0,
                            HeadshotMultiplier = 2.0,
                            LimbMultiplier = 0.75,
                            Name = "Hairpin",
                            RelativeDps = 180.0
                        },
                        new
                        {
                            Id = 14,
                            Damage = 10.0,
                            FireRate = 28.0,
                            HeadshotMultiplier = 2.0,
                            LimbMultiplier = 0.75,
                            Name = "Burletta",
                            RelativeDps = 280.0
                        },
                        new
                        {
                            Id = 15,
                            Damage = 16.0,
                            FireRate = 36.700000000000003,
                            HeadshotMultiplier = 2.0,
                            LimbMultiplier = 0.75,
                            Name = "Venator",
                            RelativeDps = 660.60000000000002
                        },
                        new
                        {
                            Id = 16,
                            Damage = 40.0,
                            FireRate = 16.300000000000001,
                            HeadshotMultiplier = 2.5,
                            LimbMultiplier = 0.75,
                            Name = "Anvil",
                            RelativeDps = 652.0
                        },
                        new
                        {
                            Id = 17,
                            Damage = 8.0,
                            FireRate = 58.299999999999997,
                            HeadshotMultiplier = 2.0,
                            LimbMultiplier = 0.75,
                            Name = "Torrente",
                            RelativeDps = 466.39999999999998
                        },
                        new
                        {
                            Id = 18,
                            Damage = 45.0,
                            FireRate = 17.699999999999999,
                            HeadshotMultiplier = 2.0,
                            LimbMultiplier = 0.75,
                            Name = "Osprey",
                            RelativeDps = 796.5
                        },
                        new
                        {
                            Id = 19,
                            Damage = 60.0,
                            FireRate = 7.7000000000000002,
                            HeadshotMultiplier = 2.0,
                            LimbMultiplier = 0.75,
                            Name = "Jupiter",
                            RelativeDps = 423.5
                        },
                        new
                        {
                            Id = 20,
                            Damage = 100.0,
                            FireRate = 20.300000000000001,
                            HeadshotMultiplier = 1.0,
                            LimbMultiplier = 0.75,
                            Name = "Hullcracker",
                            RelativeDps = 2030.0
                        },
                        new
                        {
                            Id = 21,
                            Damage = 8.0,
                            FireRate = 33.299999999999997,
                            HeadshotMultiplier = 2.0,
                            LimbMultiplier = 0.75,
                            Name = "Equalizer",
                            RelativeDps = 266.39999999999998
                        });
                });

            modelBuilder.Entity("ArcDamageCalculator.Api.Models.Shield", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Mitigation")
                        .HasColumnType("double precision");

                    b.Property<int>("Name")
                        .HasColumnType("integer");

                    b.Property<double>("TotalCharge")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Shields");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Mitigation = 0.40000000000000002,
                            Name = 0,
                            TotalCharge = 40.0
                        },
                        new
                        {
                            Id = 2,
                            Mitigation = 0.42499999999999999,
                            Name = 1,
                            TotalCharge = 70.0
                        },
                        new
                        {
                            Id = 3,
                            Mitigation = 0.52500000000000002,
                            Name = 2,
                            TotalCharge = 80.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
