// <auto-generated />
using ArcDamageCalculator.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArcDamageCalculator.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260323185033_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("ArcDamageCalculator.Api.Models.Grenade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Damage")
                        .HasColumnType("REAL");

                    b.Property<double?>("Delay")
                        .HasColumnType("REAL");

                    b.Property<double?>("Duration")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Radius")
                        .HasColumnType("REAL");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Grenades");
                });

            modelBuilder.Entity("ArcDamageCalculator.Api.Models.Gun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Damage")
                        .HasColumnType("REAL");

                    b.Property<double>("FireRate")
                        .HasColumnType("REAL");

                    b.Property<double>("HeadshotMultiplier")
                        .HasColumnType("REAL");

                    b.Property<double>("LimbMultiplier")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("RelativeDps")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Guns");
                });

            modelBuilder.Entity("ArcDamageCalculator.Api.Models.Shield", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Mitigation")
                        .HasColumnType("REAL");

                    b.Property<int>("Name")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalCharge")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Shields");
                });
#pragma warning restore 612, 618
        }
    }
}
